cooklib_django/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from cooklib_django import settings
from cook_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home.as_view(), name='home'),
    path('recipe/', views.RecipeList.as_view(), name='recipes'),
    path('recipe/<int:id>/', views.RecipeView.as_view(), name='recipe'),
    path('ingredient/<int:id>/edit/', views.IngredientEdit.as_view(), name='ingredient_edit'),
    path('ingredient/', views.ingredient_create, name='ingredient_create'),
    path('recipe/<int:id>/edit/', views.RecipeEdit.as_view(), name='recipe_edit'),
    path('ingredient/<int:id>/delete/', views.ingredient_delete, name='ingredient_delete'),
    path('recipe/<int:id>/delete/', views.recipe_delete, name='recipe_delete'),
    path('managing/', views.Managing.as_view(), name='managing'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cook_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Ingredient(models.Model):
    id = models.AutoField(primary_key=True)
    ingredient_name = models.CharField(max_length=35)
    calories_per_serving = models.IntegerField()
    image = models.ImageField(upload_to='cook_app/images/ingredients', blank=True, null=True)

    def __str__(self):
        return self.ingredient_name

    class Meta:
        db_table = 'ingredient'


class IngredientList(models.Model):
    id = models.AutoField(primary_key=True)
    amount = models.IntegerField(blank=True, null=True)
    measurement = models.CharField(max_length=10, blank=True, null=True)
    recipe = models.ForeignKey('Recipe', models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, models.CASCADE)

    def __str__(self):
        return self.ingredient.ingredient_name + ' - ' + str(self.id)

    class Meta:
        db_table = 'ingredient_list'
        unique_together = (('id', 'recipe', 'ingredient'),)


class Recipe(models.Model):
    id = models.AutoField(primary_key=True)
    dish_name = models.CharField(max_length=35)
    cooking_time = models.IntegerField(blank=True, null=True)
    image = models.ImageField(upload_to='cook_app/images/recipes', blank=True, null=True)
    description = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.dish_name

    class Meta:
        db_table = 'recipe'


class RecipeLine(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=35)
    discription = models.CharField(max_length=200)
    order_number = models.IntegerField()
    recipe = models.ForeignKey('Recipe', models.CASCADE, db_column='recipe')
    image = models.ImageField(upload_to='cook_app/images/lines', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'recipe_line'

templates/html/index.html
{% extends 'base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static 'css/index.css' %}">{% endblock %}

{% block title %}Повареная книга - Главная{% endblock %}

{% block content %}
<div class="container-fluid mt-2">
    <div class="container-sidebar">
        <div class="p-3 py-4 mb-2 text-center">
            <a href="{% url 'home' %}">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
            </a>
        </div>
        <div class="p-3 py-4 mb-2 text-center">
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-question-square"
                     viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                    <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
                </svg>
            </a>
        </div>
        <div class="p-3 py-4 mb-2 text-center">
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                </svg>
            </a>
        </div>
    </div>
    <div class="container-body">
        <div class="jumbotron jumbotron-fluid">
            <div class="container">
                <div class="display-4 text-xl-left">Библиотека простых</div>
                <div class="display-4 text-xl-left">и вкусных рецептов</div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/html/ingredient_modify.html
{% extends 'base.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href="{% static '/css/managing.css' %}">{% endblock %}

{% block title %}Повареная книга - Изменить ингридеинт - {{ ingredient.ingredient_name }}{% endblock %}

{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% load widget_tweaks %}
        <div class="form-group">
            <label for="id_ingredient_name">Название ингредиента</label>
            {% render_field form.ingredient_name class+='form-control' %}
        </div>
        <div class="form-group">
            <label for="id_calories_per_serving">Калорийность</label>
            {% render_field form.calories_per_serving class+='form-control' %}
        </div>
        {% if ingredient.image %}
        <div class="form-group">
            <label>Текущее изображение: </label>
            <a href="{{ ingredient.image.url }}" target="_blank">Ссылка</a><br>
            <input type="checkbox" name="image-clear" id="image-clear_id">
            <label for="image-clear_id">Очистить</label>
        </div>
        {% endif %}
        <div class="form-group">
            <input type="file" name="image" class="form-control-file" id="id_image" accept="image/*">
        </div>
        <button type="submit" formaction=""
                class="btn btn-success col-5">Сохранить
        </button>
        <button type="submit" formaction="{% url 'ingredient_delete' id=ingredient.id %}"
                class="btn btn-danger">Удалить ингрединет
        </button>
    </form>
</div>
{% endblock %}

templates/html/managing.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static '/css/managing.css' %}">{% endblock %}
{% block title %}Повареная книга - Управление{% endblock %}

{% block content %}
<div class="container">
    <ul class="nav nav-tabs mt-2">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#create-recipe">Новый рецепт</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="tab" href="#create-product">Добавить продукт</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
               aria-expanded="false">Редактировать рецепт</a>
            <div class="dropdown-menu">
                {% for recipe in recipes %}
                    <a class="dropdown-item" type="submit"
                       href="{% url 'recipe_edit' id=recipe.id %}">{{ recipe.dish_name }}</a>
                {% endfor %}
            </div>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
               aria-expanded="false">Редактировать ингредиент</a>
            <div class="dropdown-menu">
                {% for ingredient in ingredients %}
                    <a class="dropdown-item"
                       href="{% url 'ingredient_edit' id=ingredient.id %}">{{ ingredient.ingredient_name }}</a>
                {% endfor %}
            </div>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade active show" id="create-recipe">
            <div class="container">
                <form method="post" action="{% url 'recipes' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <input type="text" name="dish_name" class="form-control" placeholder="Название рецепта">
                        </div>
                        <div class="col">
                            <input type="text" class="form-control" name="cooking_time"
                                   placeholder="Время готовки, min">
                        </div>
                        <div class="col">
                            <input type="text" name="description" class="form-control" placeholder="Краткое описание">
                        </div>
                        <div class="col">
                            <input type="file" name="recipe_image" class="form-control-file" id="exampleFormControlFile1">
                        </div>
                    </div>
                    <div class="container">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">Ингредиент</th>
                                <th scope="col">Количество</th>
                                <th scope="col">Единица измерения</th>
                                <th scope="col">
                                    <button type="button" class="btn btn-success">Добавить</button>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for i in "1234" %}
                                <tr>
                                    <td class="block">
                                        <select class="custom-select" name="ingredient_name">
                                            <option selected value="-1">Выберите...</option>
                                            {% for ingr in ingredients %}
                                                <option value="{{ ingr.id }}">{{ ingr.ingredient_name }}</option>
                                            {% endfor %}
                                        </select>
                                    </td>
                                    <td>
                                        <input class="form-control" name="amount" type="text">
                                    </td>
                                    <td>
                                        <input class="form-control" name="measurement" type="text">
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-danger">Удалить</button>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="container">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th scope="col">Заголовок</th>
                                <th scope="col">Описание</th>
                                <th scope="col">Фото</th>
                                <th scope="col">
                                    <button type="button" class="btn btn-success">Добавить</button>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for i in "123" %}
                                <input type="hidden" name="order_number" value="{{ i }}"/>
                                <tr>
                                    <td class="block">
                                        <input class="form-control" name="title" type="text">
                                    </td>
                                    <td>
                                        <textarea class="form-control" name="step_description" id="exampleFormControlTextarea1"
                                                  rows="2"></textarea>
                                    </td>
                                    <td>
                                        <input type="file" class="form-control-file" name="step_image_{{ i }}"
                                               id="exampleFormControlFile1" accept="image/*">
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-danger">Удалить</button>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </div>
        <div class="tab-pane fade" id="create-product">
            <div class="container">
                <form method="post" action="{% url 'ingredient_create' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Название продукта</label>
                        <input type="text" name="ingredient_name" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Калорийность</label>
                        <input type="text" name="calories_per_serving" class="form-control" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlFile1">Фото</label>
                        <input type="file" name="image" class="form-control-file">
                    </div>
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/html/one_recipe.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static '/css/one_recipe.css' %}">{% endblock %}

{% block title %}Повареная книга - Рецепт - {{ recipe.dish_name }}{% endblock %}

{% block content %}
<div class="container-fluid mt-2">
    <div class="container-sidebar">
        <div class="p-3 py-4 mb-2 text-center">
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
            </a>
        </div>
        <div class="p-3 py-4 mb-2 text-center">
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-question-square"
                     viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                    <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
                </svg>
            </a>
        </div>
        <div class="p-3 py-4 mb-2 text-center">
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                </svg>
            </a>
        </div>
    </div>


    <div class="container-body">
        <div class="card">
            <div class="row g-0">
                <div class="col-md-4">
                    <img width="100%" height="100%" src="{% if recipe.image %}{{ recipe.image.url }}{% endif %}" role="img" alt="Изображение блюда">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{ recipe.dish_name }}</h5>
                        <p class="card-text">{{ recipe.description }}</p>
                        <p class="card-text"><small class="text-muted">{{ recipe.cooking_time }}m</small></p>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <table class="table caption-top">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ингредиент</th>
                    <th scope="col">Количество</th>
                </tr>
                </thead>
                <tbody>
                {% for ingredient in ingredients %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ ingredient.ingredient.ingredient_name }}</td>
                        <td>{{ ingredient.amount }} {{ ingredient.measurement }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {% for step in steps %}
            <div class="card">
                <div class="row g-0">
                    <div class="col-md-2">
                        <img width="100%" src="{% if step.image %}{{ step.image.url }}{% endif %}" role="img" alt="Изображение шага">
                    </div>
                    <div class="col-md-10">
                        <div class="card-body">
                            <h5 class="card-title">{{ step.title }}</h5>
                            <p class="card-text">{{ step.discription }}</p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/html/recipe_modify.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static '/css/managing.css' %}">{% endblock %}

{% block title %}Повареная книга - Изменить рецепт - {{ recipe.dish_name }}{% endblock %}

{% block content %}
<div class="container">
    <div class="tab-content">
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% load widget_tweaks %}
                <div class="row">
                    <div class="col">
                        {% render_field form.dish_name class+='form-control' placeholder+='Название рецепта' %}
                    </div>
                    <div class="col">
                        {% render_field form.cooking_time class+='form-control' placeholder+='Время готовки, min' %}
                    </div>
                    <div class="col">
                        {% render_field form.description class+='form-control' placeholder+='Краткое описание' %}
                    </div>
                    <div class="col">
                    <input type="file" name="image" class="form-control-file" id="id_image" accept="image/*">
                        {% if recipe.image %}
                            <label>Текущее изображение: </label>
                            <a href="{{ recipe.image.url }}" target="_blank">Ссылка</a><br>
                            <input type="checkbox" name="image-clear" id="image-clear_id">
                            <label for="image-clear_id">Очистить</label>
                        {% endif %}
                    </div>
                </div>
                <div class="container">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Ингредиент</th>
                            <th scope="col">Количество</th>
                            <th scope="col">Единица измерения</th>
                            <th scope="col">
                                <button type="button" class="btn btn-success">Добавить</button>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for ingredient in ingredients %}
                            <input type="hidden" value="{{ ingredient.id }}" name="ingredient_id"/>
                            <tr>
                                <td>
                                    <select class="custom-select" name="ingredient_name">
                                        {% for ingr in all_ingredients %}
                                            <option value="{{ ingr.id }}" {% if ingredient.ingredient.id == ingr.id %}selected{% endif %}>{{ ingr.ingredient_name }}</option>
                                        {% endfor %}
                                    </select>
                                </td>
                                <td>
                                    <input value="{{ ingredient.amount }}" class="form-control" name="amount"
                                           type="text">
                                </td>
                                <td>
                                    <input value="{{ ingredient.measurement }}" class="form-control" name="measurement"
                                           type="text">
                                </td>
                                <td>
                                    <button type="button" class="btn btn-danger">Удалить</button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="container">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Заголовок</th>
                            <th scope="col">Описание</th>
                            <th scope="col">Фото</th>
                            <th scope="col">
                                <button type="button" class="btn btn-success">Добавить</button>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for step in steps %}
                            <input type="hidden" name="order_number" value="{{ step.order_number }}"/>
                            <tr>
                                <td class="block">
                                    <input value="{{ step.title }}" class="form-control"
                                           name="title" type="text">
                                </td>
                                <td>
                                    <textarea class="form-control"
                                              name="step_description" rows="2">{{ step.discription }}</textarea>
                                </td>
                                <td>
                                    <input type="file" name="step_image_{{ step.order_number }}" class="form-control-file" id="id_step_image" accept="image/*">
                                    {% if step.image %}
                                        <label>Текущее изображение: </label>
                                        <a href="{{ step.image.url }}" target="_blank">Ссылка</a><br>
                                    {% endif %}
                                </td>
                                <td>
                                    <button class="btn btn-danger">Удалить</button>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                <button type="submit" formaction=""
                        class="btn btn-success col-5">Сохранить
                </button>
                <button type="submit" formaction="{% url 'recipe_delete' id=recipe.id %}"
                        class="btn btn-danger">Удалить рецепт
                </button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/html/recipes.html
{% extends 'base.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static '/css/recipes.css' %}">{% endblock %}

{% block title %}Повареная книга - Рецепты{% endblock %}

{% block content %}
<div class="container-fluid mt-2">
    <div class="container-sidebar">
        <div class="p-3 py-4 mb-2 text-center">
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-cart3" viewBox="0 0 16 16">
                    <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                </svg>
            </a>
        </div>
        <div class="p-3 py-4 mb-2 text-center">
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-question-square"
                     viewBox="0 0 16 16">
                    <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                    <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
                </svg>
            </a>
        </div>
        <div class="p-3 py-4 mb-2 text-center">
            <a href="#">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
                </svg>
            </a>
        </div>
    </div>



    <div class="container-body">
        <div class="card-deck">
            {% for recipe in recipes %}
                <div class="card" style="min-width: 250px;">
                    <a href="{% url 'recipe' id=recipe.id %}">
                        <img class="card-img-top" src="{{ recipe.image.url }}"
                             alt="Изображение блюда">
                    </a>
                    <div class="card-body"><h1>{{ recipe.dish_name }}</h1>{{ recipe.description }}
                    </div>
                </div>
            {% endfor %}
        </div>

    </div>
</div>

{% endblock %}